version: '3.8'

services:
  backend-test:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    ports:
      - "8001:8000"  # External:Internal
    environment:
      - POSTGRES_HOST=db-test
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_db
      - REDIS_HOST=redis-test
      - REDIS_PORT=6379
      - NODE_ENV=test
      - ENVIRONMENT=test
      - TEST_HOST=backend-test
      - TEST_PORT=8000
    volumes:
      - ./backend:/app
      - ./test-reports:/app/test-reports
      - ./scripts:/app/scripts
    depends_on:
      - db-test
      - redis-test
    networks:
      - test-network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8000"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

  db-test:
    image: postgres:15
    ports:
      - "5433:5432"  # External:Internal
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_db
    volumes:
      - pgdata-test:/var/lib/postgresql/data
    networks:
      - test-network

  redis-test:
    image: redis:7
    ports:
      - "6380:6379"  # External:Internal
    networks:
      - test-network

volumes:
  pgdata-test:

networks:
  test-network:
    name: mcp-chat-test-network 