version: '3.8'

services:
  db-test:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis-test:
    image: redis:7
    ports:
      - "6381:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend-test:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ENVIRONMENT=test
      - POSTGRES_HOST=db-test
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_db
      - REDIS_HOST=redis-test
      - REDIS_PORT=6379
      - JWT_SECRET_KEY=test_secret_key_123
      - JWT_ALGORITHM=HS256
      - LOG_LEVEL=DEBUG
    volumes:
      - .:/app
    depends_on:
      db-test:
        condition: service_healthy
      redis-test:
        condition: service_healthy 